### ISSUE TITLE
How to treat embedding layers for T5 Variant

### ISSUE THREAD

**Issue by owos** [wang-kee/LiNeS#1]
I read in the paper that you also used this method on a T5 variant model. How did you treat the embedding layer and the output layer of the model?

**Comment by wang-kee** [comment]
Hi, thanks for the interest in our work.

In both the ViT and T5 architectures, we scale the layers outside of the residual blocks by alpha, i.e. for task arithmetic, alpha is 1/num_tasks, where the weights for these layers are averaged across the models for each task.

**Comment by owos** [comment]
by residual blocks do you mean the full tansformer block (the attent layers, MLP and other artifacts in it)?  which will imply  the lm head and the nn.Embeddding layers got 0.1 as their scaling factor if alpha =0.1?

**Comment by wang-kee** [comment]
Yes exactly.
