### ISSUE TITLE
Optimal hyperparameters for multi-task merging experiments

### ISSUE THREAD

**Issue by vishaal27** [wang-kee/LiNeS#2]
Hey, 

Thanks for your great work, really cool paper!

I had a question about the optimal hyperparameters, alpha and beta required by your method for the multi-task merging experiments: would it be possible to share the hyperparameters with which you get your best results for tab. 2 and tab. 3 TA+LiNeS and TIES+LiNeS, for all model sizes and task-numbers?

That would be of great help.

Thanks!

**Comment by wang-kee** [comment]
Hi, thanks a lot for your interest in our work!

We'd like to emphasize that for multi-task merging, we only tune beta while alpha is set as a heuristic value, as discussed in Section 5.2 (Equation 2) in the paper. As a result, applying LiNeS search for only hyper-parameter, which has the same computational cost as the base methods.

For the vision experiments, we list the optimal parameters for each setting in the following table:

![image](https://github.com/user-attachments/assets/62e313cd-cc6b-4d4f-a1c7-78fd5e556c2b)

Note that you can set `specify_lambda` to skip the hyper-parameter searching process in the evaluation script, e.g., you can call `python main.py model=ViT-B-32 num_tasks=8 method="sum" method.apply_lines=True specify_lambda=0.3` which directly sets lambda to 0.3. However, we would encourage searching the hyper-parameters as well when reproducing the experiments, to account for any potential difference in the environment.

Please let us know if you have any other questions.
